package it.unicam.cs.agrotrace.util.mapper.file;

import it.unicam.cs.agrotrace.shared.entity.file.ImageEntity;
import it.unicam.cs.agrotrace.shared.model.file.Image;
import it.unicam.cs.agrotrace.util.mapper.RepositoryMapper;
import org.springframework.stereotype.Component;

import java.nio.file.Path;

@Component
public class ImageMapper implements RepositoryMapper<Image, ImageEntity> {

    @Override
    public ImageEntity entityFromModel(Image model) {
        ImageEntity entity = new ImageEntity();
        entity.setId(null); // ID is generated by the database
        entity.setPath(model.getPath().toString());
        entity.setDescription(model.getDescription());
        return entity;
    }

    @Override
    public Image modelFromEntity(ImageEntity entity) {
        return Image.builder()
                .id(entity.getId())
                .path(Path.of(entity.getPath()))
                .description(entity.getDescription())
                .build();
    }
}
